# Generated by Django 2.2.14 on 2021-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210924_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(blank=True,null=True,auto_now_add=True),
        ),
    ]
