# Generated by Django 2.2.14 on 2021-09-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210924_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
           name='date_created',
           
        ),
    ]
