# Generated by Django 2.2.14 on 2021-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(blank=True,null=True,auto_now_add=True),
        ),
    ]
